// Chess quotes shown by Kael around the app (from Chess quotes.docx).
export const QUOTES = [
  { q: "Chess is mental torture.", a: "Garry Kasparov" },
  { q: "Success is the result of deep preparation, relentless work, and learning from failure.", a: "Garry Kasparov" },
  { q: "Attackers may sometimes regret bad moves, but it is much worse to forever regret an opportunity you allowed to pass.", a: "Garry Kasparov" },
  { q: "One does not succeed by sticking to convention.", a: "Garry Kasparov" },
  { q: "The goal of modern chess is not simply to win—it is to improve.", a: "Garry Kasparov" },
  { q: "I don't believe in psychology. I believe in good moves.", a: "Bobby Fischer" },
  { q: "Chess is life.", a: "Bobby Fischer" },
  { q: "Chess is war over the board. The object is to crush the opponent's mind.", a: "Bobby Fischer" },
  { q: "Tactics flow from a superior position.", a: "Bobby Fischer" },
  { q: "You have to have the fighting spirit.", a: "Bobby Fischer" },
  { q: "Without the element of enjoyment, it is not worth trying to excel at anything.", a: "Magnus Carlsen" },
  { q: "Some people think that if their opponent plays a beautiful game, it's okay to lose. I don't.", a: "Magnus Carlsen" },
  { q: "You have to be merciless.", a: "Magnus Carlsen" },
  { q: "There is no formula to become World Champion. Just keep improving.", a: "Magnus Carlsen" },
  { q: "Every game teaches you something.", a: "Magnus Carlsen" },
  { q: "When you see a good move, look for a better one.", a: "Emanuel Lasker" },
  { q: "The hardest game to win is a won game.", a: "Emanuel Lasker" },
  { q: "On the chessboard lies and hypocrisy do not survive long.", a: "Emanuel Lasker" },
  { q: "A player who is determined to improve can never stop learning.", a: "Emanuel Lasker" },
  { q: "The purpose of study is understanding, not memorization.", a: "Emanuel Lasker" },
  { q: "You may learn much more from a game you lose than from a game you win.", a: "José Raúl Capablanca" },
  { q: "A good player is always lucky.", a: "José Raúl Capablanca" },
  { q: "To improve, analyze your losses.", a: "José Raúl Capablanca" },
  { q: "In order to improve your game, you must study the endgame.", a: "José Raúl Capablanca" },
  { q: "The player who understands the position wins.", a: "José Raúl Capablanca" },
  { q: "There are two kinds of sacrifices: correct ones and mine.", a: "Mikhail Tal" },
  { q: "You must take your opponent into a deep dark forest where two plus two equals five.", a: "Mikhail Tal" },
  { q: "If you are going to make a mistake, make it boldly.", a: "Mikhail Tal" },
  { q: "Complications favor the better prepared.", a: "Mikhail Tal" },
  { q: "Creativity wins games.", a: "Mikhail Tal" },
  { q: "If you wait long enough, your opponent will make a mistake.", a: "Anatoly Karpov" },
  { q: "Chess is everything: art, science, and sport.", a: "Anatoly Karpov" },
  { q: "Avoid mistakes before looking for brilliant moves.", a: "Anatoly Karpov" },
  { q: "Patience is often stronger than aggression.", a: "Anatoly Karpov" },
  { q: "The smallest advantage is worth fighting for.", a: "Anatoly Karpov" },
  { q: "Chess cannot be taught. Chess can only be learned.", a: "Mikhail Botvinnik" },
  { q: "Practice should always have a purpose.", a: "Mikhail Botvinnik" },
  { q: "Talent alone is never enough.", a: "Mikhail Botvinnik" },
  { q: "Discipline creates champions.", a: "Mikhail Botvinnik" },
  { q: "Preparation is half the battle.", a: "Mikhail Botvinnik" },
  { q: "The king is a fighting piece.", a: "Wilhelm Steinitz" },
  { q: "A sacrifice is best refuted by accepting it.", a: "Wilhelm Steinitz" },
  { q: "Attack only after obtaining an advantage.", a: "Wilhelm Steinitz" },
  { q: "Every attack must have a foundation.", a: "Wilhelm Steinitz" },
  { q: "Position comes before combinations.", a: "Wilhelm Steinitz" },
  { q: "Chess, like love, like music, has the power to make men happy.", a: "Siegbert Tarrasch" },
  { q: "Before the endgame, the gods have placed the middlegame.", a: "Siegbert Tarrasch" },
  { q: "Mistakes are inevitable; improvement is optional.", a: "Siegbert Tarrasch" },
  { q: "Every move should improve your position.", a: "Siegbert Tarrasch" },
  { q: "Development is the soul of the opening.", a: "Siegbert Tarrasch" },
  { q: "The winner is the one who makes the next-to-last mistake.", a: "Savielly Tartakower" },
  { q: "The blunders are all there on the board waiting to be made.", a: "Savielly Tartakower" },
  { q: "Tactics is knowing what to do when there is something to do; strategy is knowing what to do when there is nothing to do.", a: "Savielly Tartakower" },
  { q: "No game was ever won by resigning.", a: "Savielly Tartakower" },
  { q: "Some part of every mistake is always correct.", a: "Savielly Tartakower" },
  { q: "Help your pieces so they can help you.", a: "Paul Morphy" },
  { q: "The ability to play chess is the sign of a gentleman.", a: "Paul Morphy" },
  { q: "Rapid development is the key to success.", a: "Paul Morphy" },
  { q: "Time is often worth more than material.", a: "Paul Morphy" },
  { q: "Every move should have a purpose.", a: "Paul Morphy" },
  { q: "The threat is stronger than the execution.", a: "Aron Nimzowitsch" },
  { q: "First restrain, then blockade, then destroy.", a: "Aron Nimzowitsch" },
  { q: "Prophylaxis wins games.", a: "Aron Nimzowitsch" },
  { q: "A weak square never disappears.", a: "Aron Nimzowitsch" },
  { q: "Small advantages become decisive.", a: "Aron Nimzowitsch" },
  { q: "Never stop fighting.", a: "Viktor Korchnoi" },
  { q: "Every position contains hidden resources.", a: "Viktor Korchnoi" },
  { q: "The game isn't over until the handshake.", a: "Viktor Korchnoi" },
  { q: "Determination beats talent when talent gives up.", a: "Viktor Korchnoi" },
  { q: "Resilience creates champions.", a: "Viktor Korchnoi" },
  { q: "The only person who never makes mistakes is the one who never does anything.", a: "Vladimir Kramnik" },
  { q: "Objectivity is the strongest weapon.", a: "Vladimir Kramnik" },
  { q: "You improve by questioning yourself.", a: "Vladimir Kramnik" },
  { q: "Study your weaknesses first.", a: "Vladimir Kramnik" },
  { q: "Consistency beats inspiration.", a: "Vladimir Kramnik" },
  { q: "Every match is the most important one.", a: "Viswanathan Anand" },
  { q: "Hard work eventually becomes intuition.", a: "Viswanathan Anand" },
  { q: "Preparation builds confidence.", a: "Viswanathan Anand" },
  { q: "Learning never ends.", a: "Viswanathan Anand" },
  { q: "Respect every opponent.", a: "Viswanathan Anand" },
  { q: "Only severe self-criticism leads to improvement.", a: "Alexander Kotov" },
  { q: "Look for unusual moves.", a: "Alexander Kotov" },
  { q: "Calculate before you move.", a: "Alexander Kotov" },
  { q: "Discipline your thinking.", a: "Alexander Kotov" },
  { q: "Training your mind is the key.", a: "Alexander Kotov" },
  { q: "The most powerful weapon in chess is to have the next move.", a: "David Bronstein" },
  { q: "Imagination creates opportunities.", a: "David Bronstein" },
  { q: "Every position contains possibilities.", a: "David Bronstein" },
  { q: "Chess rewards curiosity.", a: "David Bronstein" },
  { q: "Play with courage.", a: "David Bronstein" },
  { q: "Every chess master was once a beginner.", a: "Irving Chernev" },
  { q: "The difference between masters and amateurs is persistence.", a: "Irving Chernev" },
  { q: "Learn from every game.", a: "Irving Chernev" },
  { q: "Every mistake is a lesson.", a: "Irving Chernev" },
  { q: "The journey to mastery never ends.", a: "Irving Chernev" },
  { q: "Pawns are the soul of chess.", a: "François-André Danican Philidor" },
  { q: "Play the opening like a book, the middlegame like a magician, and the endgame like a machine.", a: "Rudolf Spielmann" },
  { q: "Chess is the struggle against error.", a: "Johannes Zukertort" },
  { q: "We learn by chess the habit of not being discouraged by present bad appearances.", a: "Benjamin Franklin" },
  { q: "Pawn endings are to chess what putting is to golf.", a: "Cecil Purdy" },
  { q: "In order to improve your game, you must study the endgame before everything else.", a: "José Raúl Capablanca" },
  { q: "The endgame can be studied and mastered by itself.", a: "José Raúl Capablanca" },
  { q: "Only after studying the endgame should one proceed to the opening.", a: "José Raúl Capablanca" },
  { q: "It has been my experience that players who do not study regularly never fulfill their potential.", a: "Emanuel Lasker" },
  { q: "The purpose of study is understanding.", a: "Emanuel Lasker" },
  { q: "A player must work every day.", a: "Mikhail Botvinnik" },
  { q: "The strongest players are those who analyze their own games.", a: "Mikhail Botvinnik" },
  { q: "Training without analysis is wasted effort.", a: "Mikhail Botvinnik" },
  { q: "Analyze every game you lose.", a: "Alexander Kotov" },
  { q: "The habit of analysis separates masters from amateurs.", a: "Alexander Kotov" },
  { q: "Calculation is a skill that must be trained.", a: "Alexander Kotov" },
  { q: "Talent is no substitute for systematic work.", a: "Mark Dvoretsky" },
  { q: "The strongest players never stop learning.", a: "Mark Dvoretsky" },
  { q: "Study should always have a clear objective.", a: "Mark Dvoretsky" },
  { q: "Deep understanding is more valuable than memorization.", a: "Mark Dvoretsky" },
  { q: "Mistakes are your greatest teachers.", a: "Mark Dvoretsky" },
  { q: "Chess improvement comes from understanding ideas, not memorizing moves.", a: "Jeremy Silman" },
  { q: "Every imbalance tells you where to look.", a: "Jeremy Silman" },
  { q: "Knowledge without practice disappears.", a: "Jeremy Silman" },
  { q: "Every chess player has thousands of mistakes waiting to be corrected.", a: "Yasser Seirawan" },
  { q: "Improvement begins with honest self-evaluation.", a: "Yasser Seirawan" },
  { q: "The board is your greatest teacher.", a: "Yasser Seirawan" },
  { q: "The beauty of chess begins in the endgame.", a: "José Raúl Capablanca" },
  { q: "Simple positions reveal true understanding.", a: "José Raúl Capablanca" },
  { q: "The endgame is the poetry of chess.", a: "Akiba Rubinstein" },
  { q: "A player's real strength appears in the ending.", a: "Mikhail Botvinnik" },
  { q: "One extra tempo in the endgame may decide everything.", a: "Paul Keres" },
  { q: "Study endings until they become second nature.", a: "Cecil Purdy" },
  { q: "The endgame teaches precision.", a: "Yuri Averbakh" },
  { q: "Technique wins games.", a: "Yuri Averbakh" },
  { q: "Chess is an art.", a: "Siegbert Tarrasch" },
  { q: "Chess is an art that expresses the science of logic.", a: "Vladimir Kramnik" },
  { q: "Chess combines sport, science and art.", a: "Garry Kasparov" },
  { q: "Chess is an art of analysis.", a: "David Bronstein" },
  { q: "Beauty in chess is born from imagination.", a: "David Bronstein" },
  { q: "You must bring your imagination to the board.", a: "Mikhail Tal" },
  { q: "There is nothing more beautiful than an unexpected sacrifice.", a: "Mikhail Tal" },
  { q: "Chess is poetry.", a: "Richard Réti" },
  { q: "While all artists are not chess players, all chess players are artists.", a: "Marcel Duchamp" },
  { q: "Chess has all the beauty of art—and much more.", a: "Marcel Duchamp" },
  { q: "Chess is a fairy tale of one thousand and one blunders.", a: "Savielly Tartakower" },
  { q: "The game of chess is like a love affair.", a: "Frank Marshall" },
  { q: "Chess is the intellectual romance.", a: "Richard Réti" },
  { q: "You learn more from losing than from winning.", a: "Capablanca" },
  { q: "A player who thinks he knows everything has already stopped improving.", a: "Lasker" },
  { q: "Nobody ever won a chess game by resigning.", a: "Bobby Fischer" },
  { q: "Fight until the last move.", a: "Korchnoi" },
  { q: "Losing hurts, but it teaches.", a: "Magnus Carlsen" },
  { q: "Training is the bridge between talent and mastery.", a: "Dvoretsky" },
  { q: "Success depends on preparation.", a: "Kasparov" },
  { q: "Study your own games first.", a: "Fischer" },
  { q: "A sacrifice should inspire confidence.", a: "Tal" },
  { q: "Creativity wins more games than memorization.", a: "Tal" },
  { q: "Imagination is stronger than memory.", a: "Bronstein" },
  { q: "Chess rewards courage.", a: "Kasparov" },
  { q: "Better an interesting mistake than a boring truth.", a: "Larsen" },
  { q: "Good judgment comes from experience.", a: "Lasker" },
  { q: "Think before calculating.", a: "Kotov" },
  { q: "Prophylaxis is the highest form of strategy.", a: "Nimzowitsch" },
  { q: "Chess demands total concentration.", a: "Fischer" },
  { q: "Every master was once a beginner.", a: "Chernev" },
  { q: "Understanding beats memorization.", a: "Silman" },
  { q: "Study your losses.", a: "Seirawan" },
  { q: "Improvement never ends.", a: "Dvoretsky" },
  { q: "Question your own ideas.", a: "Kramnik" },
  { q: "Chess is the gymnasium of the mind.", a: "Blaise Pascal (often attributed, though the attribution is disputed)" },
  { q: "Chess teaches foresight.", a: "Benjamin Franklin" },
  { q: "Chess teaches caution.", a: "Benjamin Franklin" },
  { q: "Chess teaches perseverance.", a: "Benjamin Franklin" },
  { q: "Chess teaches the consequences of actions.", a: "Benjamin Franklin" },
  { q: "Life is like a game of chess.", a: "Miguel de Cervantes (commonly attributed)" },
  { q: "The board never lies.", a: "Common chess saying" },
  { q: "Every position deserves respect.", a: "Common master advice" },
  { q: "The pieces know the truth.", a: "Modern coaching saying" },
  { q: "Patience is a chess player's greatest weapon.", a: "Common coaching maxim" },
  { q: "There are no shortcuts to mastery.", a: "Common coaching maxim" },
  { q: "One move can change everything.", a: "Chess proverb" },
  { q: "The best move is usually the hardest to find.", a: "Common master advice" },
  { q: "A beautiful game is remembered longer than an easy victory.", a: "Common chess saying" },
  { q: "Every mistake is tuition.", a: "Modern coaching saying" },
  { q: "Study deeply, play boldly.", a: "Modern coaching maxim" },
  { q: "Knowledge becomes strength only through practice.", a: "Coaching maxim" },
  { q: "Champions analyze; amateurs justify.", a: "Modern coaching saying" },
  { q: "Progress comes one game at a time.", a: "Coaching maxim" },
  { q: "The board reflects your thinking.", a: "Instructional saying" },
  { q: "A strong endgame gives confidence throughout the game.", a: "Instructional principle" },
  { q: "Pattern recognition is earned, not inherited.", a: "Modern training principle" },
  { q: "Every great player is a lifelong student.", a: "Instructional saying" },
  { q: "Chess is not merely a game—it is a lifelong conversation between knowledge, creativity, and character.", a: "Modern chess philosophy" },
];

// Kael's own encouragement, bilingual — mixed in with the historical quotes
// above so the pop-ups aren't always someone else's words.
export const KAEL_LINES = {
  es: [
    '¡Cada partida que juegas te hace un poco más fuerte!',
    'No hay derrota que no enseñe algo — sigue analizando.',
    '¿Ya calentaste hoy con un par de puzzles?',
    'Los grandes maestros también empezaron sin saber mover un caballo.',
    'Un pequeño avance cada día se convierte en una gran mejora.',
    'Recuerda: cada error es una lección, no un fracaso.',
    '¡Tu racha te está esperando! No la dejes enfriar.',
    'La paciencia en el tablero también se entrena fuera de él.',
    'Hoy es un buen día para estudiar un final.',
    'Sigue así — estoy orgulloso de tu progreso.',
    '¿Sabías que revisar tus partidas perdidas es el estudio más valioso?',
    'Un movimiento tranquilo a veces vale más que un sacrificio brillante.',
  ],
  en: [
    "Every game you play makes you a little stronger!",
    "There's no loss that doesn't teach something — keep analyzing.",
    'Warmed up with a puzzle or two today?',
    "Every grandmaster once didn't know how to move a knight.",
    'A small improvement each day adds up to real progress.',
    'Remember: every mistake is a lesson, not a failure.',
    'Your streak is waiting for you — don\'t let it go cold!',
    'Patience on the board is trained off the board too.',
    'Today is a good day to study an endgame.',
    "Keep it up — I'm proud of your progress.",
    'Did you know reviewing your losses is the most valuable study you can do?',
    'A quiet move is sometimes worth more than a brilliant sacrifice.',
  ],
};

// Shown when a puzzle is solved.
export const KAEL_PRAISE = {
  es: [
    '¡Excelente! Encontraste la jugada correcta.',
    '¡Muy bien! Ese golpe táctico no se te escapó.',
    '¡Impresionante! Sigue así.',
    '¡Perfecto! Tu visión táctica está mejorando.',
    '¡Genial! Un paso más hacia la maestría.',
    '¡Bravo! Esa era la idea exacta.',
    '¡Así se hace! Puzzle resuelto con estilo.',
    '¡Excelente cálculo!',
    '¡Lo lograste! Cada puzzle te hace más fuerte.',
    '¡Fantástico! Tu entrenamiento está dando frutos.',
    '¡Precisión total! Bien jugado.',
    '¡Sigue con ese ritmo, vas muy bien!',
  ],
  en: [
    'Excellent! You found the right move.',
    "Well done! That tactic didn't get past you.",
    'Impressive! Keep it up.',
    'Perfect! Your tactical vision is improving.',
    'Great job! One step closer to mastery.',
    'Bravo! That was exactly the idea.',
    'That’s how it’s done! Puzzle solved in style.',
    'Excellent calculation!',
    'You got it! Every puzzle makes you stronger.',
    'Fantastic! Your training is paying off.',
    'Total precision! Well played.',
    "Keep that pace up, you're doing great!",
  ],
};

// Shown on the first wrong try of a puzzle — encouragement, not scolding.
export const KAEL_MISTAKE = {
  es: [
    'No pasa nada, inténtalo de nuevo — mira bien las amenazas.',
    'Casi. Vuelve a revisar la posición con calma.',
    'Un tropiezo no es una caída. ¡Sigue buscando!',
    'Esa no era, pero vas por buen camino. Inténtalo otra vez.',
    'Respira y mira el tablero de nuevo — la jugada está ahí.',
    'Cada intento te acerca a la solución. ¡Tú puedes!',
    'No te rindas, los mejores también fallan antes de acertar.',
    'Revisa las piezas que están en juego — hay algo que se te escapa.',
  ],
  en: [
    "No worries, try again — look closely at the threats.",
    'So close. Take another calm look at the position.',
    "A stumble isn't a fall. Keep searching!",
    "That wasn't it, but you're on the right track. Try again.",
    'Take a breath and look at the board again — the move is there.',
    "Every attempt gets you closer to the solution. You've got this!",
    'Even the best miss before they find it. Keep going.',
    "Check which pieces are in play — you're missing something.",
  ],
};

// Shown if a puzzle has been open for a while without being solved.
export const KAEL_CHECKIN = {
  es: { text: '¿Todo bien? Llevas un rato aquí. ¿Quieres un pequeño empujón?', okBtn: 'Sí, dame una pista', dismissBtn: 'Estoy bien, sigo pensando' },
  en: { text: "Everything OK? You've been on this one a while. Want a little nudge?", okBtn: 'Yes, give me a hint', dismissBtn: "I'm fine, still thinking" },
};

// Shown when a Blindfold puzzle starts — encourages solving without peeking.
export const KAEL_BLINDFOLD = {
  es: [
    'Confía en tu tablero mental — puedes verlo sin verlo.',
    'Visualiza cada casilla. Tú puedes con esto.',
    'Respira, imagina el tablero pieza por pieza. ¡Eres capaz!',
    'Los grandes maestros calculan así — sin mirar. Tú también puedes.',
    'No necesitas los ojos, necesitas tu memoria. ¡Confía en ella!',
  ],
  en: [
    'Trust your mental board — you can see it without seeing it.',
    'Visualize every square. You can do this.',
    'Breathe, picture the board piece by piece. You are capable!',
    'Grandmasters calculate just like this — blindfolded. So can you.',
    "You don't need your eyes, you need your memory. Trust it!",
  ],
};

// First-time warning before using a hint (peek) in Blindfold mode.
export const KAEL_HINT_WARNING = {
  es: { text: 'Un aviso de Kael: si usas la pista, el ELO que ganes al resolver este puzzle será menor. ¡Inténtalo de memoria primero!', okBtn: 'Entendido', dismissBtn: 'Cancelar' },
  en: { text: "A note from Kael: if you use the hint, the ELO you earn for solving this puzzle will be lower. Try it from memory first!", okBtn: 'Got it', dismissBtn: 'Cancel' },
};

// Shown atop the post-game Game Review, picked by outcome.
export const KAEL_GAME_REVIEW = {
  win: {
    es: [
      '¡Buena partida! Construiste tu ventaja con paciencia.',
      '¡Victoria! Vamos a ver qué jugadas hicieron la diferencia.',
      '¡Bien jugado! Revisemos los momentos clave de la partida.',
    ],
    en: [
      'Good game! You built your advantage with patience.',
      'A win! Let\'s see which moves made the difference.',
      'Well played! Let\'s look at the key moments of the game.',
    ],
  },
  loss: {
    es: [
      'No salió como querías, pero cada partida enseña algo. Repasemos juntos.',
      'Una derrota es solo información. Veamos dónde se torció la partida.',
      'Ánimo — revisemos qué pasó y qué puedes mejorar la próxima vez.',
    ],
    en: [
      "It didn't go your way, but every game teaches something. Let's review it together.",
      "A loss is just information. Let's see where the game turned.",
      "Chin up — let's look at what happened and what to improve next time.",
    ],
  },
  draw: {
    es: [
      'Tablas — una partida bien equilibrada. Veamos los detalles.',
      'Empate reñido. Repasemos los momentos más ajustados.',
    ],
    en: [
      "A draw — a well-balanced game. Let's see the details.",
      "A hard-fought draw. Let's review the tightest moments.",
    ],
  },
};
