// Generated by tools/reminder/make-vapid-keys.mjs. The PUBLIC half of the Web
// Push signing key. Not a secret. Changing it drops every existing subscription.
export const VAPID_PUBLIC_KEY = 'BG0vI6j_oPS_T2s9R5viZhCHkBfNhLrTHkcrhsP7ETi0catVP_t4n8dhUdawcD_vpEplRlbQ-rR9OH9at94cLCc';
